### PR TITLE
set erase_tag_set to true even if list of tags is empty

### PR DESCRIPTION
**Pull request by lotharschulz**
'erase_tag_set = True' even if list of tags is empty

related: #411

### CODE REVIEW

**Comment by hjacobs** [comment]
This change looks dangerous to me (without knowing the details)...

**Comment by mikkeloscar** [comment]
This would always erase the volume if we don't find any tags.

Isn't this the opposite of what you want?

**Comment by Raffo** [comment]
I thought the same of what @mikkeloscar and @hjacobs said, this is also why I suggest doing something like @dryewo originally suggested in the issue.

**Comment by lotharschulz** [comment]
learned today about `already_mounted` variable (https://github.com/lotharschulz/taupage/blob/master/runtime/opt/taupage/init.d/10-prepare-disks.py#L252) is most likely different than I expected it.

**Pull request closed without merging**
