### PR TITLE
Update td-agent version to latest (3.4.1-0)

### PR DESCRIPTION
**Pull request by pheanex**
This ships fluentd in version 1.4.2

### CODE REVIEW

**Comment by pheanex** [comment]
:+1:

**Comment by femueller** [comment]
👍

**Comment by femueller** [comment]
Looks good to me

**Comment by aermakov-zalando** [comment]
👍

**Comment by anton-ryzhov** [comment]
Why 1.4.2 and not 1.5.2?
How `td-agent=3.4.1-0` means `fluentd=1.4.2`?

**Pull request merged**
