### PR TITLE
Add application_logrotate_disable_compress

### PR DESCRIPTION
**Pull request by ruiaraujo**
Compression of the previous application.log was hindering Fashion Store skipper.

This was happening despite `rotate 0`.

### CODE REVIEW

**Comment by szuecs** [comment]
please sign your commit to make DCO check happy and travis says:
```
3.4 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (7) Failed to connect to s3.amazonaws.com port 443: Connection timed out
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```

**Comment by ruiaraujo** [comment]
:+1:

**Comment by femueller** [comment]
👍

**Comment by femueller** [comment]
👍

**Comment by ruiaraujo** [comment]
:+1:

**Pull request merged**
