### PR TITLE
#229 mount var/log as read-write

### LINKED ISSUE #229: mount log directory as read-write in order to write custom log files
```
# mount logdirectory as read-write in order to write custom log files
    if config.get('mount_var_log'):
        yield '-v'
        yield '/var/log:/var/log'
```

### PR DESCRIPTION
**Pull request by mrandi**
fixes #229

### CODE REVIEW

**Comment by apfeiffer85** [comment]
:+1:

**Comment by tuxlife** [comment]
:-1:

**Comment by tuxlife** [comment]
With this fix is it possible to change and remove the taupage systemlogs

**Comment by apfeiffer85** [comment]
ok so we have to use some different directory for custom logs like /var/log/custom or something similar.

**Comment by apfeiffer85** [comment]
we now only mount /var/log/custom as read-write

**Comment by mrandi** [comment]
👍

**Comment by tuxlife** [comment]
@apfeiffer85  Why did you need /var/log from the host under /var/log in docker?

Why not /var/log-docker/:/var/log and /var/log:/var/log-host?

**Comment by apfeiffer85** [comment]
i guess there are some use cases where Teams need read access to /var/log/application.log and maybe other log files therefore was the read-only mount (this was already implemented). 
And i guess there is no really need to mount /var/log into /var/log in the docker container it just was because of common place for logs. 
We could definitely change this to something else like /var/log-host or anything else.

But what do you mean with /var/log-docker:/var/log ? 

What we also did was to add a custom logdir /var/log/custom for custom application logs so we only mount /var/log/custom as read-write. But we also could mount this into /var/log-host/custom . This is necessary because the log shipping agents running on the host system and they can only follow logs from the host system ( or lets say it is easier to follow logs on the host system ).

**Comment by tuxlife** [comment]
:+1:

**Comment by apfeiffer85** [comment]
New Solution is now: 

mount /var/log from host system to the container dir /var/log-host (read-only)
And any custom logs will be saved at /var/log-custom (host system) and mounted as read-write to the container /var/log

**Pull request merged**
