### PR TITLE
upgrade local planb-tokeninfo

### PR DESCRIPTION
**Pull request by harti2006**
This will now support the Zalando Platform IAM tokens.

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by linki** [comment]
@jbellmann still in progress?

**Comment by hjacobs** [comment]
@harti2006 binary files are hard to check :smile: , but "LGTM"

**Comment by harti2006** [comment]
@linki haha, no, the "in progress" label comes automatically from waffle.io https://waffle.io/zalando-stups/taupage
It just uses the access token from @jbellmann

**Comment by ChristianLohmann** [comment]
👍

**Pull request merged**
