### PR TITLE
Fix log message when waiting for EBS volume

### PR DESCRIPTION
**Pull request by a1exsh**
Signed-off-by: Oleksandr Shulgin <oleksandr.shulgin@zalando.de>

1. Make sure we report the number of second to sleep correctly.
2. Use `INFO` level: error is already reported one log line above.

### CODE REVIEW

**Comment by a1exsh** [comment]
This is a follow-up to #508.
The failure is not introduced by me, seems like master is broken:
```
ImportError: No module named 'google_compute_engine'
```

**Comment by aermakov-zalando** [comment]
Looks like a Travis issue, I'll have a look.

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
