### PR TITLE
set application user id explicitly…

### PR DESCRIPTION
**Pull request by jbspeakr**
… and move implicit nvidia-docker user creation to where it does not interfere 
-> see #392

### CODE REVIEW

**Comment by hjacobs** [comment]
Maybe add a test to check that the uid is as expected (spec tests are in `tests/` folder).

**Comment by jbspeakr** [comment]
of course, it's on its way 😎

**Comment by jbspeakr** [comment]
are the serverspec tests actually run by travis? couldn't find a corresponding config/ output...

**Comment by a1exsh** [comment]
:+1:

**Comment by hjacobs** [comment]
@jbspeakr the tests are run by our internal Go CD pipeline (it actually creates an AMI and starts up an EC2 instance).

**Comment by jbspeakr** [comment]
@hjacobs ah, that's nice – so I'll lay checking that pipeline into your hands ;D

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
