### PR TITLE
Add NVIDIA driver and CUDA support to Taupage [work in progress]

### LINKED ISSUE #240: Add support for GPU-based instances
For machine learning applications, it would be useful to have access to the AWS GPU instances.

Note that the installation of CUDA is delegated to the docker images, and thus the only overhead added to the AMI iteself is the NVIDIA driver. This means that additional space requirements are reduced. What are the limitations for STUPS AMIs?
- Image generation: 
  - Install the NVIDIA driver.
- Runtime (when running on a g2.2xlarge): 
  -  Ensure that relevant device nodes are created.
  -  Modify the docker launch parameters to map devices and drivers to docker container.
- Testing:
  - Create a simple test GPU-based docker image to test the driver installation.
  - Ensure that the driver does not interfere on instances where no GPU devices are present.

Note that `g2.2xlarge` instances are required to run GPU applications on AWS. I must still confirm whether this is a strict requirement when building the AMI.

References:
- NVIDIA docker discussion on installing drivers on AWS: https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2
- Arguments for mapping drivers and devices to docker containers: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
- Creating device nodes when X11 is not present: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications

### PR DESCRIPTION
**Pull request by elezar**
Closes #240.

This PR adds the NVIDIA driver (and CUDA support) to Taupage. This should allow for GPU instances to be used for compute intensive applications such as machine learning, while still maintaining the audit compliance provided by Taupage.

Note that the installation of CUDA is delegated to the docker images, and thus the only overhead added to the AMI iteself is the NVIDIA driver. This means that additional space requirements are reduced. What are the limitations for STUPS AMIs?
- Image generation: 
  - [x] Install the NVIDIA driver.
- Runtime (when running on a g2.2xlarge): 
  - [x] Ensure that relevant device nodes are created.
  - [x] Modify the docker launch parameters to map devices and drivers to docker container.
- Testing:
  - [ ] Create a simple test GPU-based docker image to test the driver installation.
  - [ ] Ensure that the driver does not interfere on instances where no GPU devices are present.

Note that `g2.2xlarge` instances are required to run GPU applications on AWS. I must still confirm whether this is a strict requirement when building the AMI.

References:
- NVIDIA docker discussion on installing drivers on AWS: https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2
- Arguments for mapping drivers and devices to docker containers: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
- Creating device nodes when X11 is not present: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications

### CODE REVIEW

**Comment by elezar** [comment]
I had a discussion with @femueller offline regarding this, and he suggested I submit a PR. Since this is my first one to Taupage, any comments or suggestions would be welcome. 

I see for example from Zappr that my commit messages don't match the required form. I'm assuming this means that I should be referencing an issue in them. Does this mean that I should create an issue first and move discussion there?

**Comment by femueller** [comment]
Since we don't have a zappr config file in here, I've disabled the commit message check. Maybe we'll check for a message pattern in the future. https://zappr.readthedocs.io/en/latest/setup/#commitmessages
It should be fixed in the next commit.

**Comment by elezar** [comment]
Thanks. I will make a dummy commit so that this can be toggled.

From my side, all the parts seem to be there, and I was able to run a GPU-based docker container (using Docker.py) on a g2.2xlarge instance when ssh-ing into the instance directly (running `create-ami.sh` with the `--dry-run` option). However, when I restart the instance, then things don't seem to work as expected.

I have also tried to launch an instance with the specified AMI using senza, but this also does not succeed. Any tip on how to test/debug this further would be greatly appreciated.

An example Dockerfile could contain:
```
FROM nvidia/cuda

RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-samples-$CUDA_PKG_VERSION && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/cuda/samples/1_Utilities/deviceQuery
RUN make

COPY scm-source.json /

CMD ./deviceQuery
```

**Comment by femueller** [comment]
Does the syslog show something interesting?

**Comment by elezar** [comment]
The syslog doesn't show much. There are a lot of errors with regards to other STUPS tooling, but nothing  GPU specific.

I think I should move the creation of the nvidia device nodes to an upstart script in /etc/init instead of coupling it so tightly to taupage.

**Comment by elezar** [comment]
Has someone had a chance to look into these changes? Are there other ways in which I can test this?

**Comment by szuecs** [comment]
@elezar It will take some time. Can you create an issue for this PR, please? Every PR should be discussed in an issue before. Thanks!

**Comment by elezar** [comment]
@szuecs as there was no CONTRIBUTING.md file, I was not sure whether it was required for first create an issue. I have created #240 to track this.

**Comment by szuecs** [comment]
@elezar Thanks!

**Comment by elezar** [comment]
I am closing this as it has been superseded by @fatz's work on #365

**Comment by elezar** [comment]
Opening this again. It can be closed as soon as #365 has been finalised.

**Comment by elezar** [comment]
:-1:

**Comment by elezar** [comment]
Since #365 has been merged, I am closing this PR. Thanks @fatz for your efforts!

**Pull request closed without merging**
