### PR TITLE
fixed scalyr agent file pickup

### PR DESCRIPTION
**Pull request by vwiessner**
fixed scalyr agent file pickup in /opt/taupage/init.d/01-register-scalyr-agent.sh

Signed-off-by: Veit Wiessner <veit.wiessner@zalando.de>

### CODE REVIEW

**Comment by femueller** [comment]
👍

**Comment by a1exsh** [comment]
/me is wondering where's that unit-test? :thinking:

**Comment by femueller** [comment]
The test seems to fail because of something different than the feature that has been added.
Looks like that there are flake errors for the script `10-prepare-disks.py`.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by femueller** [comment]
👍

**Pull request merged**
