### PR TITLE
disable AppD logging per default

### PR DESCRIPTION
**Pull request by apfeiffer85**
since Scalyr is now our central logging Provider, AppD is now per default disabled.

### CODE REVIEW

**Comment by apfeiffer85** [comment]
I also add this option to the STUPS documentation: https://github.com/zalando-stups/documentation/pull/113

**Comment by tuxlife** [comment]
@apfeiffer85 What is the behavior for _old_ application (without update of the senza yaml)

**Comment by tuxlife** [comment]
@apfeiffer85 Please disable AppD logging only, if scalyr logging is enabled

**Comment by apfeiffer85** [comment]
👍

**Pull request merged**
