### PR TITLE
Fix the function call when docker start fails

### PR DESCRIPTION
**Pull request by arjunrn**
The #519 change added masking of all KMS encrypted values. But the error message which prints the command was not updated to use the updated function, which causes and exception. This PR fixes the issue.

### CODE REVIEW

**Comment by arjunrn** [comment]
@aermakov-zalando Can you approve?

**Comment by arjunrn** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
Oops, sorry!

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
