### PR TITLE
update cloudwatch scripts

### PR DESCRIPTION
**Pull request by mce**
Currently cloudwatch scripts can't push memory&disk metrics using IAM role credentials. Looks like latest version of the scripts supports IAM roles. 

With this, we can create auto scaling policies based on memory usage.

https://forums.aws.amazon.com/message.jspa?messageID=422894
https://aws.amazon.com/code/8720044071969977

### CODE REVIEW

**Comment by tuxlife** [comment]
:+1:

**Comment by tuxlife** [comment]
@mce can you please update your branch? after then we can merge the pr

**Comment by mce** [comment]
@tuxlife done 👍

**Comment by tuxlife** [comment]
:+1:

**Pull request merged**
