### PR TITLE
enhanced log locations

### PR DESCRIPTION
**Pull request by drummerwolli**
fixes https://github.com/zalando-stups/taupage/issues/143

### CODE REVIEW

**Comment by hjacobs** [comment]
@apfeiffer85 @femueller let's discuss this PR first before merging (you are the Taupage maintainers)

**Comment by femueller** [comment]
:+1: for a discussion too. We will get this done very soon.

**Comment by chutium** [comment]
any update on this? we really need this, not only for kafka, but also for spark appliance user or Elasticsearch appliance user like @marek-obuchowicz mentioned https://github.com/zalando-stups/taupage/issues/143#issuecomment-149206785, I believe for Spilo or cassandra, pushing multiple log files to scalyr or something is also meaningful.

tail -f is an option, but for a long running service, if the log file rotated (old log file switch to xxx.log.1 or something, and a new xxx.log created), its inode changed, tail -f will not working after that

**Comment by marek-obuchowicz** [comment]
@chutium maybe you can use this library to quickly create a "multiple logfiles tail" tool: http://code.activestate.com/recipes/577968-log-watcher-tail-f-log/ - it handles correctly logfile rotation

**Comment by apfeiffer85** [comment]
We don't want to do this pull request because thats brings a lot of more maintenance to the Taupage system. 
Also the logrotate is not included and therefore it is possible to write the disk full of logs. 

But at the end we need a solution for your case, maybe we can tag the logs and set a different log parser but we have to discuss that with Scalyr or maybe other Logging Providers.

**Pull request closed without merging**
