### PR TITLE
add option to include necessary scala classes in AppDynamics 

### PR DESCRIPTION
**Pull request by apfeiffer85**
issue #237

### CODE REVIEW

**Comment by Raffo** [comment]
@apfeiffer85 Can you explain a bit more the changes? I don't have a way to prove they are right and so I cannot merge the PR. Also, I saw the comment by @hjacobs on the documentation, we can maybe also address it here where the PR lives.

**Comment by apfeiffer85** [comment]
@Raffo the PR is about to change the default configuration from the AppDynamics JVM Agent. And i also answer to the question in the documentation. Unfortunately there is no better way to do this. :( 
And this must be optional because if we change this to every single JVM Agent these can cause performances issues. So only Scala/play/akka Applications need this modifications.

**Comment by Raffo** [comment]
Well, it's good then.

**Comment by Raffo** [comment]
LGTM

**Pull request merged**
