### PR TITLE
#212 prohibit latest and SNAPSHOT Docker image tags

### LINKED ISSUE #212: Prohibit using mutable *-SNAPSHOT Docker images
I don't think we should remove the SNAPSHOT feature from Pier One (https://github.com/zalando-stups/pierone/issues/74), rather, reject them with Taupage (abort startup) then we still keep the sharing between team members.

### PR DESCRIPTION
**Pull request by hjacobs**
Disallow mutable Docker image tags such as `latest` or `*-SNAPSHOT`.

Fixes #212.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
Do we want to ban other registries as well, by the way? Or do we want to still rely on fullstop for that?

**Comment by hjacobs** [comment]
@aermakov-zalando yeah, I guess we could whitelist registries, but that needs some configuration option. I went with this simple first step.

**Pull request merged**
