### PR TITLE
use iid as default

### PR DESCRIPTION
**Pull request by tuxlife**
Change defautl behavior of `registry_login` and change to pierone iid login

### CODE REVIEW

**Comment by tuxlife** [comment]
@hjacobs Can we remove the hole `get_token` function from `taupage/__init__.py`?

**Comment by hjacobs** [comment]
@tuxlife yes, if it's no longer used in `Docker.py`...

**Comment by hjacobs** [comment]
:+1:

**Comment by tuxlife** [comment]
:+1:

**Pull request merged**
