### PR TITLE
Updated docker version

### PR DESCRIPTION
**Pull request by arjunrn**
The repository from where docker is downloaded will be [shutdown soon](https://github.com/moby/moby/issues/40466). Better upgrade now than later.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Is the `nvidia-docker` version compatible, or do we need to pin it as well?

**Comment by aermakov-zalando** [comment]
👍

**Comment by arjunrn** [comment]
@aermakov-zalando Don't know about the `nvidia-docker` but we have an e2e test now and it will fail if it's not compatible.

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
