### PR TITLE
Add ELB health check

### PR DESCRIPTION
**Pull request by marco-hoyer**
This PR provides the capability for an instance to check it's state with an ELB. This prevents a rolling update to proceed before an ELB really states an instance to be in service. We implemented a flexible mechanism, equal to the runtime configuration, to allow different health checks for different use cases.
There are also some changes to simplify testing and minor reliability improvements in init.sh.
As usual I this is a proposal to be discussed. If you think that this change is good for you, I will add some documentation.

### CODE REVIEW

**Comment by hjacobs** [comment]
@marco-hoyer thanks for PR! Could you check the Travis CI build? I guess it needs to be ./run-tests.sh in the travis YAML?

**Comment by marco-hoyer** [comment]
@hjacobs yes, you're right. I also fixed s small typo. Works now.

**Comment by marco-hoyer** [comment]
Hi guys, any suggestions about this?

**Comment by hjacobs** [comment]
@marco-hoyer thanks. I hope @femueller or @apfeiffer85 can take a look at it (?)

**Comment by femueller** [comment]
I think we can definitely merge this. @marco-hoyer Could you fix the merge conflicts again please?

**Comment by marco-hoyer** [comment]
Finally managed to fix conflicts.

**Comment by femueller** [comment]
:+1: thank you @marco-hoyer

**Pull request merged**
