### PR TITLE
Add vmstat to node exporter

### PR DESCRIPTION
**Pull request by csenol**

### CODE REVIEW

**Comment by femueller** [comment]
Looks good to me

**Comment by femueller** [comment]
This has to be reinvestigated. Apparently adding this option it breaks the tests. I've rolled this back.

**Comment by csenol** [comment]
@femueller Is there another way to get context switches from taupage ?

**Comment by femueller** [comment]
@csenol I'll look into it again. Maybe we just have to update the node exporter to make it work.

**Pull request merged**
