### PR TITLE
remove copytruncate from logrotate

### PR DESCRIPTION
**Pull request by pheanex**
In order to not lose any logs during rotation

### CODE REVIEW

**Comment by pheanex** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
Should restart of agent also be removed here?

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by pheanex** [comment]
:+1:

**Comment by pheanex** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
:+1:

**Pull request merged**
