### PR TITLE
Added sysstat and htop packages (#400) for basic performance analysis

### PR DESCRIPTION
**Pull request by bocytko**
Added sysstat and htop packages (#400) for basic performance analysis.

### CODE REVIEW

**Comment by Raffo** [comment]
htop doesn't seem so necessary to me. I can understand the need for something like what is contained in sysstat though.

**Comment by bocytko** [comment]
I'm fine with removing `htop`. Should I adjust the PR?

**Comment by tuxlife** [comment]
:+1:

**Comment by Raffo** [comment]
@bocytko from a quick check `htop` is really small, so we can get it in! Thanks for your PR.

**Comment by Raffo** [comment]
👍

**Pull request merged**
