### PR TITLE
Moved common logging attributes to server_attributes

### PR DESCRIPTION
**Pull request by beverage**
Per-log attributes are counted as log volume per log line.

### CODE REVIEW

**Comment by femueller** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
Can you add AWS account ID and region if you're modifying this anyway? They should be available from the instance identity document at http://169.254.169.254/latest/dynamic/instance-identity/document.

**Comment by aermakov-zalando** [comment]
And please consider making the script readable with the help of `jq` or `python`. :)

**Comment by aermakov-zalando** [comment]
What happens if an instance is terminated and then another one is started with a different stack but the same IP address as the previous one? Will the attributes be overwritten completely or will I have two different servers in the list?

**Comment by beverage** [comment]
You will have the same serverHost as taupage sets it to the application id.  You will get a second stack name in the list.  ServerHost is something that should probably never be queried on for this reason - I am not sure why, long ago, it was made redundant with application_id.

**Comment by femueller** [comment]
👍

**Comment by femueller** [comment]
:+1:

**Comment by beverage** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
